language: python

sudo: false

cache:
  directories:
  - .eggs

python:
  - "2.7"
  - "3.4"
  #- "3.5" # Not supported yet
  - "pypy"

env:
  - DJANGO_VERSION=1.7
  - DJANGO_VERSION=1.8
  - DJANGO_VERSION=1.9

install:
  - pip install coveralls flake8
  - pip install django==${DJANGO_VERSION}

script:
  - coverage run --branch --source=revproxy setup.py test
  - flake8 revproxy
  - coverage report --fail-under=100 --show-missing

after_script:
  - coveralls
