language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"

env:
  - DJANGO_VERSION=1.6.8
  - DJANGO_VERSION=1.7.1

install:
  - pip install coveralls flake8
  - pip install django==${DJANGO_VERSION}

script:
  - coverage run --source=revproxy setup.py test
  - flake8 revproxy
  - coverage report --fail-under=100 --show-missing
  - coveralls
