language: python

sudo: false

cache:
  directories:
  - .eggs

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"

env:
  - DJANGO_VERSION=1.6.11
  - DJANGO_VERSION=1.7.8
  - DJANGO_VERSION=1.8.1

install:
  - pip install coveralls flake8
  - pip install django==${DJANGO_VERSION}

script:
  - coverage run --source=revproxy setup.py test
  - flake8 revproxy
  - coverage report --fail-under=100 --show-missing

after_script:
  - coveralls
